crate_name = "permissions-ex"
crate_version = "0.1"
policy_version = "0.1"

[[statements]]
type = "Require"
region = "permissions-ex::remove(path)"
effect = "fs::delete(path)"

[[statements]]
type = "Require"
region = "permissions-ex::save_data(path)"
effect = "fs::create(path)"

[[statements]]
type = "Require"
region = "permissions-ex::save_data(path)"
effect = "fs::write(path)"

[[statements]]
type = "Allow"
region = "permissions-ex::remove(path)"
effect = "process::exec(rm -f path)"

[[statements]]
type = "Allow"
region = "permissions-ex::save_data(path)"
effect = "fs::delete(path)"

[[statements]]
type = "Allow"
region = "permissions-ex::prepare_data()"
effect = "fs::append(my_app.log)"
