crate_name = "permissions_ex"
crate_version = "0.1"
policy_version = "0.1"

[[statements]]
type = "Require"
region = "permissions_ex::remove(path)"
effect = "std::fs(path)"

[[statements]]
type = "Require"
region = "permissions_ex::save_data(path)"
effect = "std::fs(path)"

[[statements]]
type = "Require"
region = "permissions_ex::save_data(path)"
effect = "std::fs(path)"

[[statements]]
type = "Allow"
region = "permissions_ex::remove(path)"
effect = "std::process(rm -f path)"

[[statements]]
type = "Allow"
region = "permissions_ex::save_data(path)"
effect = "std::fs(path)"

[[statements]]
type = "Allow"
region = "permissions_ex::prepare_data()"
effect = "std::fs(my_app.log)"
