crate_name = "rustc_version"
crate_version = "0.1"
policy_version = "0.1"

[[statements]]
type = "Allow"
region = "rustc_version(*)"
effect = "std::env(\"RUSTC\")"

[[statements]]
type = "Allow"
region = "rustc_version(*)"
effect = "std::env(\"RUSTC\")"

[[statements]]
type = "Allow"
region = "rustc_version(*)"
effect = "std::process([\"rustc\", \"-vV\"])"

[[statements]]
type = "Allow"
region = "rustc_version(*)"
effect = "std::process([RUSTC, \"-vV\"])"

[[statements]]
type = "Allow"
region = "VersionMeta::for_command(cmd)"
effect = "exec([cmd, \"-vV\"])"
