name: Checks

on:
  push:
    paths: [ 'src/**', 'tests/**', '.github/workflows/checks.yml' ]
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run Clippy
      run: cargo clippy -- -D warnings

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Rustfmt
        run: cargo fmt -- --check

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run unit tests
        run: cargo test
