name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cargo check
      run: cargo check

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run Clippy
      run: cargo clippy -- -D warnings

  install-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Make install
      run: make install

  install-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Make install
      run: make install

  tests:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build release
      run: cargo build --release

    - name: Update test results
      run: make test-results

    - name: Check for differences
      run: git diff --exit-code

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Formatting Check
        run: cargo fmt -- --check
