name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run Clippy
      run: cargo clippy -- -D warnings

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Rustfmt
        run: cargo fmt -- --check

  install-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Make install
      run: make install

  install-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Make install
      run: make install

  tests:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build release
      run: cargo build --release

    - name: Update test results
      run: make test-results

    - name: Check for differences
      id: git-check
      run: |
        git diff --exit-code data/results
        echo "::set-output name=changes::$(if [ $? -eq 1 ]; then echo 'true'; else echo 'false'; fi)"

    - name: Configure Git
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --global user.name 'Caleb Stanford'
        git config --global user.email 'cdstanford@ucdavis.com'

    - name: Commit and push if there are changes
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git add data/results
        git commit -m "Update test results"
        git push
