name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y make
        apt-get install -y pkg-config libssl-dev

    - name: Cargo check
      run: cargo check

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y make
        apt-get install -y pkg-config libssl-dev

    - name: Install Clippy
      run: rustup component add clippy

    - name: Run Clippy
      run: cargo clippy -- -D warnings

  install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y make
        apt-get install -y pkg-config libssl-dev

    - name: Make install
      run: make install

  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y make
        apt-get install -y pkg-config libssl-dev

    - name: Install Python
      run: apt-get install -y python3

    - name: Build release
      run: cargo build --release

    - name: Update test results
      run: make test-results

    - name: Check for differences
      run: git diff --exit-code

  fmt:
    runs-on: ubuntu-latest
    container: rust:slim

    steps:
      - uses: actions/checkout@v3

      - name: Install Rustfmt
        run: rustup component add rustfmt

      - name: Formatting Check
        run: cargo fmt -- --check
