name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container: rust:slim

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make install

    - name: Run check
      run: make checks

    - name: Update test results
      run: make test-results

  fmt:

    runs-on: ubuntu-latest

    container: rust:slim

    steps:
      - uses: actions/checkout@v3
      - name: Formatting Check
        run: cargo fmt -- --check
